### ISSUE TITLE
User lists are showing lots of duplicate users

### ISSUE THREAD

**Issue by terriko** [python-gsoc/python-blogs#368] opened 2020-03-26 22:45 UTC
Right now, we wind up with user entries every time an invite is sent out.  We probably shouldn't do that and should instead collapse user lists so there's only one per email.

**Comment by botanicvelious** [comment] 2020-03-27 02:18
Duplicate of #365 there should only be one user profile per user per organization per year however it would make sense to have some better list of users for example all mentors for current year etc

**Closed as completed** 2020-04-27 07:51 UTC
